apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reactapp
  description: React App for Presentation
  annotations: 
        backstage.io/techdocs-ref: url:https://github.com/Fasttrack-Dev/backstage-demo-dokumentation
spec:
  type: website
  lifecycle: experimental
  owner: joseidon
